### ISSUE TITLE
Change hosts file locks script

### ISSUE THREAD

**Issue by l8nit3tr0ubl3** [crombiecrunch/yiimp_install_scrypt#6]
Hello,
Thank you for your hard work on this script. The issue I am reporting is not a very big one, but causes the script to fail.
To reproduce:
-Ubuntu 16.04, new user with sudo privileges
-Set locales
-install git, screen and curl
-Run script with "set hosts file" option

Issue:
Script hangs indefinitely at first step "Updating host file".

Workaround:
Set no for changing hosts file and all runs cleanly :) So i will just make the hosts changes myself :)

<edit>
May have located the issue on my own, the server came with apache pre-installed as I am also getting bind 80 errors.
I will re-install server and remove apache and re-run then update here :)

**Comment by crombiecrunch** [comment]
Yes due to the several ways a server can initially be configured, Ive removed the hosts option to prevent this. 

Thanks for reporting.
