### ISSUE TITLE
yiimp-reloaded repository not found

### ISSUE THREAD

**Issue by asktomsk** [crombiecrunch/yiimp_install_scrypt#7]
git clone https://github.com/crombiecrunch/yiimp-reloaded.git

Cloning into 'yiimp-reloaded'...
remote: Repository not found.
fatal: repository 'https://github.com/crombiecrunch/yiimp-reloaded.git/' not found

**Comment by crombiecrunch** [comment]
leaked code for the next version, code was changed back
